server:
  port: 8012

spring:
  application:
    name: finance-server
  datasource:
    driver-class-name: org.postgresql.Driver
    password: yjts9tian
    url: jdbc:postgresql://192.168.20.170:5432/smart-inventory?currentSchema=task
    username: yjts

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
